fixes(#10): replace test-logger implementation
abacaphiliac/doctrine-psr-sql-logger pull request #12
Opened 2020-01-16 03:33 UTC by abacaphiliac

per https://packagist.org/packages/gamez/psr-testlogger

2020-01-16 03:43 UTC, abacaphiliac commented
@holtkamp was this what you had in mind? unfortunately, the PSR TestLogger is only available since `psr/log:^1.1`.

2020-01-16 08:26 UTC, holtkamp commented on test/PsrSqlLoggerIntegrationTest.php
>      private function getRecordByIndex($index)
Maybe instead of using a `@return \stdClass`, use a return type `: \stdClass`?

2020-01-16 08:27 UTC, holtkamp requested changes
Yeah indeed, I would suggest to use return types where possible, for example:

```php
private function getRecordByIndex($index) : \stdClass
```

2020-01-18 21:01 UTC, abacaphiliac commented
@holtkamp ah, of course! carry-over from `php:<7` : (

i have made the changes!

2020-01-20 11:12 UTC, holtkamp approved these changes

2020-01-22 03:40 UTC, merged